# Generated by Django 3.1.7 on 2021-06-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='user',
        ),
    ]
