# Generated by Django 3.1.7 on 2021-06-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20210606_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messages',
            new_name='message',
        ),
    ]
